config/routes.rb
Rails.application.routes.draw do

  get 'sitemap.xml', :to => 'sitemap#index', :defaults => {:format => 'xml'}

  get 'upcoming_events/index'

  get 'past_events/index'

  resources :schedules
  get "schedules/detail/:room_id" => "schedules#detail", as: :detail

  namespace :api, defaults: { format: :json }  do
    namespace :v1 do
      resources :schedules, :only => [:index,:show, :create, :update]
      post "receive/xendit" => "receive#xendit"
      get "receive/xendit" => "receive#xendit"
    end
  end

  namespace :managers do
    get 'books/index'
  end

  namespace :id do
    resources :blogs, :only => [:index, :show]
  end

  mount_roboto
  mount Ckeditor::Engine => '/ckeditor'
  resources :benefits, :only => [:index, :show]
  resources :careers, :only => [:index, :show]
  resources :schoolpreneurs, controller:'evhive_classes', :only => [:index, :show]
  resources :evhive_connects, :only => [:index,:create]
  resources :authors, :only => [:show]
  resources :partners, :only => [:index, :show]
  resources :events, :only => [:index, :show]
  resources :blogs, :only => [:index, :show]
  resources :categories, :only => [:show]
  resources :promos, :only => [:index, :show]
  resources :subscribes, :only => [:create]
  get 'tags/:tag', to: 'blogs#index', as: "tag"

  resources :books
  resources :payments
  resources :enquiries
  namespace :managers do
    root to: 'dashboard#index'
    resources :plans, :buildings, :locations, :blogs,:categories, :events, :benefits, :rooms,:report, :dashboard, :books, :careers, :partners, :evhive_classes, :evhive_connects, :schedules, :enquiries, :promos, :payments, :authors
    get "report/paid/:id" => "report#paid", as: :set_paid
    get "report/destroy/:id" => "report#destroy", as: :set_destroy
  end

  devise_for :managers
  resources :subscriptions do
    collection do
      get 'thank_you/:id' => "subscriptions#thank_you", as: :sub_thank
    end
  end
  resources :dashboard

  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    :sessions => "users/sessions"
  }
  resources :locations
  resources :buildings
  resources :plans

  get 'about' => 'home#about'
  get 'press' => 'blogs#press'
  get 'enquiry' => 'enquiries#new'
  get 'privacy_policy' => 'home#privacy_policy'
  get 'thank_you' => 'home#thank_you'
  get 'student_ambassador' => 'home#student_ambassador'
  get 'creative-studio', to: 'plans#creative_studio'
  get 'meeting-room', to: 'plans#meeting_room'
  get 'event-space', to: 'plans#event_space'
  get '/past_events' => 'past_events#index'
  root to: 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @futures = Event.where('date >= ?', Date.today).order(date: :desc)
  end

  def about
  end

  def student_ambassador
  end

  def creative_studio
  end

  def privacy_policy
  end

  def thank_you

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_event.html.erb
 <div class="owl-carousel owl-theme event-slider">
    <% @futures.last(5).each do |event|%>
      <div class="item">
      <%= link_to(event) do %>
        <%= image_tag event.banner.url(:original), :class => "img-responsive"%>
        <div class="overlay-image">
        </div>
      <% end %>  
      </div>
    <% end %>
</div>

  

<!--<div class="col-md-3 col-xs-12 no-gutter">
    <%#= link_to(event) do %>
    <%#= image_tag event.banner.url(:original), :class => "img-responsive"%>
    <div class="overlay-image">
      <h4><%#= event.title %></h4>
    </div>
    <%# end %>
  </div>-->

app/views/home/about.html.erb
<section>
	<div class="jumbo-small bg-about"></div>
</section>

<section>
	<div class="container-fluid">
		<img src="/assets/home/img/header/why_cowork.png" alt="" width="100%">
	</div>
	<div class="container ptop pbottom">
		<div class="row">
			<div class="col-xs-12 col-md-6 col-md-push-6">
				<img src="/assets/home/img/all/whycowork1.jpg" width="100%" alt="">
			</div>
			<div class="col-xs-12 col-md-6 col-md-pull-6">
				<h3 class="title-header"><img src="/assets/home/img/icon/Professional.png" width="40" alt=""> Professional Surroundings</h3>
				<hr class="line-left line-black">
				<p class="text-justify">
					Why sit all alone at home or work in cubicles when you can work amongst productive people of all backgrounds? Increase your insights and acquire new inspirations. Mingle with other coworkers and take a break whenever you feel like taking one. Inspire and be inspired by the people around you.
				</p>
				<%= link_to "Book Now", plans_path, class:'btn btn1', :onclick => "ga('send','event','Click','Book Now');"%>
			</div>
		</div>
	</div>
</section>

<section>
	<div class="container-fluid bg-lightgrey">
		<div class="container">
			<div class="row ptop pbottom">
				<div class="col-md-6">
					<img src="/assets/home/img/all/whycowork2.jpg" alt="" width="100%">
				</div>
				<div class="col-md-6">
					<h3 class="title-header text-right"><img src="/assets/home/img/icon/build_network.png" width="40" alt=""> Build Your Network</h3>
					<hr class="line-right line-black">
					<p class="text-justify">
						Collaboration is the key to all successful stories, networking is organic when the connection is not forced upon. In our coworking spaces, you will never know who you’ll encounter everyday. With an open space concept, the option of networking is not forced upon but merely a choice. You will not want to miss our events that range from self-enriching workshops to Game of Throne viewing nights.
					</p>
					<p class="text-right"><%= link_to "Book Now", plans_path, class:'btn btn1', :onclick => "ga('send','event','Click','Book Now');"%></p>
				</div>
			</div>
		</div>
	</div>
</section>

<section>
	<div class="container-fluid">
		<div class="container">
			<div class="container ptop pbottom">
				<div class="row">
					<div class="col-xs-12 col-md-6 col-md-push-6">
						<img src="/assets/home/img/all/whycowork3.jpg" width="100%" alt="">
					</div>

					<div class="col-xs-12 col-md-6 col-md-pull-6">
						<h3 class="title-header"><img src="/assets/home/img/icon/affordable.png" width="40" alt=""> Affordable</h3>
						<hr class="line-left line-black">
						<p class="text-justify">
							Building your own startup or managing your ongoing company is already as difficult as it is, let us help you take one burden off by offering you an affordable and flexible price plan for all your needs. You don’t have to worry about additional fees when printing, beverages, and high-speed internet is part of the packaged deal. 
						</p>
						<%= link_to "Book Now", plans_path, class:'btn btn1', :onclick => "ga('send','event','Click','Book Now');"%>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section>
	<div class="container-fluid bg-lightgrey">
		<div class="container">
			<div class="row ptop pbottom">
				<div class="col-md-6">
					<img src="/assets/home/img/all/whycowork4.jpg" alt="" width="100%">
				</div>
				<div class="col-md-6">
					<h3 class="title-header text-right"><img src="/assets/home/img/icon/environment.png" width="40" alt=""> Environment</h3>
					<hr class="line-right line-black">
					<p class="text-justify">
						A burn out is unavoidable when you are stuck in a boring routine. Make everyday a different day by working in EV Hive! With a young and dynamic vibe, you will never feel bored or trapped. With desk chairs, bean bags, long desks and even quiet rooms for self-thinking, comfort should be our middle name. Open concepts and barrier-less workspaces provides a better productivity for your daily tasks. 
					</p>
					<p class="text-right"><%= link_to "Book Now", plans_path, class:'btn btn1', :onclick => "ga('send','event','Click','Book Now');"%></p>
				</div>
			</div>
		</div>
	</div>
</section>

<section>
	<div class="container-fluid no-gutter">
    <img src="/assets/home/img/header/Happening.png" alt="" width="100%">
  </div>

	<div class="container">
		<div class="gallery">
			<div class="row">
				<div class="owl-carousel owl-theme">
					<div class="item">
						<a href="/assets/home/img/gallery/Event1.jpg" data-title="Join our bunch of workshops, events and classes for an environment that will invigorate your team every day." data-lightbox="gallery">
							<img src="/assets/home/img/gallery/Event1.jpg" height="200" class="img-thumbnail">
						</a>
					</div>
					<div class="item">
						<a href="/assets/home/img/gallery/Event2.jpg" data-title="End your work-day to gain more insights and knowledge about Technology, Arts, Fin-tech and much more. We hold events with speakers who are masters in their fields." data-lightbox="gallery">
							<img src="/assets/home/img/gallery/Event2.jpg" height="200" class="img-thumbnail">
						</a>
					</div>
					<div class="item">
						<a href="/assets/home/img/gallery/Event3.jpg" data-title="No time for the gym? EV Hive loves to partner up with Ride Jakarta to give you the feel of WORK-ing out after your busy day" data-lightbox="gallery">
							<img src="/assets/home/img/gallery/Event3.jpg" height="200" class="img-thumbnail">
						</a>
					</div>
					<div class="item">
						<a href="/assets/home/img/gallery/Event4.jpg" data-title="You will benefit from a diverse and global community that provides guidance, resources, and opportunities shared between all EV Hive members." data-lightbox="gallery">
							<img src="/assets/home/img/gallery/Event4.jpg" height="200" class="img-thumbnail">
						</a>
					</div>
					<div class="item">
						<a href="/assets/home/img/gallery/Event5.jpg" data-title="Meet and connect with new potential collaborators and share private discussions with our speakers for a better understanding of the workshop." data-lightbox="gallery">
							<img src="/assets/home/img/gallery/Event5.jpg" height="200" class="img-thumbnail">
						</a>
					</div>
					<div class="item">
						<a href="/assets/home/img/gallery/Event6.jpg" data-title="Share private discussions with our speakers for a better understanding of the workshop." data-lightbox="gallery">
							<img src="/assets/home/img/gallery/Event6.jpg" height="200" class="img-thumbnail">
						</a>
					</div>
					<div class="item">
						<a href="/assets/home/img/gallery/Event7.jpg" data-title="A few months ago, Djarot visited our JSC space and gave us words that makes our coworking space a place worthy of admiration." data-lightbox="gallery">
							<img src="/assets/home/img/gallery/Event7.jpg" height="200" class="img-thumbnail">
						</a>
					</div>
					<div class="item">
						<a href="/assets/home/img/gallery/Event8.jpg" data-title="Our members are welcome to host an event in one of our flexible event spaces. Share your passion and let our members be inspired!" data-lightbox="gallery">
							<img src="/assets/home/img/gallery/Event8.jpg" height="200" class="img-thumbnail">
						</a>
					</div>
					<div class="item">
						<a href="/assets/home/img/gallery/Space1.jpg" data-title="Breath in our open-air natural lighting spaces that give you the touch of a modern coworking environment." data-lightbox="gallery">
							<img src="/assets/home/img/gallery/Space1.jpg" height="200" class="img-thumbnail">
						</a>
					</div>
					<div class="item">
						<a href="/assets/home/img/gallery/Space2.jpg" data-title="EV Hive is a place where anyone can rent a comfortable space to work in, with an opportunity for collaboration with members of different companies and projects." data-lightbox="gallery">
							<img src="/assets/home/img/gallery/Space2.jpg" height="200" class="img-thumbnail">
						</a>
					</div>
					<div class="item">
						<a href="/assets/home/img/gallery/Space3.jpg" data-title="Our interior, service, and facilities will surely satisfy your coworking game! With strategic locations, it is accessible for you and your coworkers." data-lightbox="gallery">
							<img src="/assets/home/img/gallery/Space3.jpg" height="200" class="img-thumbnail">
						</a>
					</div>
					<div class="item">
						<a href="/assets/home/img/gallery/Space4.jpg" data-title="With our fun working environment, you will find yourself enjoying your time while finishing off your tasks and responsibilities." data-lightbox="gallery">
							<img src="/assets/home/img/gallery/Space4.jpg" height="200" class="img-thumbnail">
						</a>
					</div>
				</div><!--end of slider-->
			</div>
		</div>
	</div>
	 <%= javascript_include_tag 'application'%>
</section>

<section>
	<div class="container-fluid bg-lightgrey">
		<h3 class="text-center">Our Space Supported By</h3>
		<div class="container">
			<div class="sponsors">
				<div class="owl-carousel owl-theme">
					<div class="item">
						<img src="/assets/home/img/sponsors/bookabuku.png"  width="150">
					</div>
					<div class="item">
						<img src="/assets/home/img/sponsors/bwi.png"  width="150">
					</div>
					<div class="item">
						<img src="/assets/home/img/sponsors/campina.png"  width="150">
					</div>
					<div class="item">
						<img src="/assets/home/img/sponsors/cisco.png"  width="150">
					</div>
					<div class="item">
						<img src="/assets/home/img/sponsors/docco.png"  width="150">
					</div>
					<div class="item">
						<img src="/assets/home/img/sponsors/hobo.png"  width="150">
					</div>
					<div class="item">
						<img src="/assets/home/img/sponsors/holycozy.png"  width="150">
					</div>
					<div class="item">
						<img src="/assets/home/img/sponsors/lemonilo.png"  width="150">
					</div>
					<div class="item">
						<img src="/assets/home/img/sponsors/magnet.png"  width="150">
					</div>
					<div class="item">
						<img src="/assets/home/img/sponsors/Osakamoo.png"  width="150">
					</div>
					<div class="item">
						<img src="/assets/home/img/sponsors/perfect health.png"  width="150">
					</div>
					<div class="item">
						<img src="/assets/home/img/sponsors/Prost.png"  width="150">
					</div>
					<div class="item">
						<img src="/assets/home/img/sponsors/Redbull.png"  width="150">
					</div>
					<div class="item">
						<img src="/assets/home/img/sponsors/Sekopi.png"  width="150">
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<script>
	/*$('.gallery a').lightBox({
    fixedNavigation: true,
		resizeDuration: 200,
      wrapAround: true,
			fitImagesInViewport:true,
			alwaysShowNavOnTouchDevices:true
	});*/
	$(document).ready(function(){
		$(".gallery .owl-carousel").owlCarousel({
			itemsDesktop : [1199,3],
      itemsDesktopSmall : [980,2],
      itemsTablet: [768,1],
      itemsTabletSmall: false,
      itemsMobile : [479,1],
      autoPlay:5000,
      items:3,
      navigation:true
    });

		$(".sponsors .owl-carousel").owlCarousel({
			itemsDesktop : [1199,6],
      itemsDesktopSmall : [980,5],
      itemsTablet: [768,2],
      itemsTabletSmall: false,
      itemsMobile : [479,2],
			navigation:false,
			autoPlay:3000,
			items: 6
		});
	});
</script>

app/views/home/index.html.erb
<%= content_for(:title, "Coworking Space in Jakarta, Indonesia - Affordable Office Room | EV Hive") %>
<%= content_for(:meta_description, "A Perfect Coworking Space in Jakarta & Tangerang | Shared Desk | Starting Rp 50.000/day | Private Office | Meeting Room | Event Space | Community | Book Now!") %>

<%# <section>
  <div id="promoModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        
        
        <div class="modal-body">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <a href="https://a.pgtb.me/hvRNsp" target="_blank">
            <img src="/assets/home/img/promo/EVHIVE DIGITAL PROMO MAY 1080x1080.jpg" alt="EVHIVE-DIGITAL-PROMO-MAY-2018" width="100%" height="auto">
          </a>
          
        </div>
        
      </div>

    </div>
  </div>
</section> %>

<section>
  <div class="jumbotron bg1">
    <div class="container">
      <div class="col-md-6 col-xs-10 heading">
        <h1 class="text-left title-header">Begin Now</h1>
        <p class="text-left"><hr class="line-left"></p>
        <p class="text-justify lead sub-header">
          Offices without cubicles and workspaces with no walls; A coworking space in Jakarta & Medan, Indonesia, where you can work to the beat of your own drums, be surrounded by inspiration and network with the best.
        </p>
        <%# <%= link_to "Book Now", plans_path, :class => "btn btn1 btn-lg btn-cta", :onclick => "ga('send','event','Click','Book Now');"%>
        <a href="https://cohive.space" class="btn btn1 btn-lg btn-cta" ><i class="fa fa-globe"></i></span> Go to CoHive</a>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container-fluid no-gutter">
    <img src="/assets/home/img/header/Happening.png" alt="Whats Happening in Coworking Space" width="100%">
  </div>
  <div class="container-fluid">
    <!--events start-->
    <div class="row">
      <%= render "event" %>
      
    </div>
    
  <!--event ends-->
</section>

<section>
  <div class="container-fluid">
    <img src="/assets/home/img/header/why_cowork1.png" alt="" style="width:100%">
  </div>

  <!--Desktop Version-->
  <div class="row bg-grey wrapper-scroll">
    <!--Value-->
    <div class="col-md-6 font-white" id="value">
      <div id="val">
        <div class="text-center">
          <img src="/assets/home/img/icon/value.png" height="60">
          <h2 class="title-header">One fits all</h2>
          <hr class="line">
        </div>
        <p class="text-justify">
          A coworking space in Indonesia, especially Jakarta & Medan, with a one price solution for all your necessities: meeting rooms, fiber-optic internet, printing and freeflow gourmet coffee. Affordable, convenient, professional. Hassle-free coworking spaces in Jakarta that offers you the flexibility you need. With futuristic workspaces that boosts your productivity, inspiration is a blink away. 
        </p>
        <p class="text-center p15">Why pay extra when you can pay less for more?</p>
        <p class="text-center ptop"><%= link_to "Book Now", plans_path, :class => "btn btn1", :onclick => "ga('send','event','Click','Book Now');"%></p>
      </div>

      <!--future-->
      <div id="fut">
        <div class="text-center">
          <img src="/assets/home/img/icon/the_future.png" height="60">
          <h2 class="title-header">Work hard, play hard..</h2>
          <hr class="line">
        </div>
        <p class="text-justify">
          Work hard or play hard? Why not both? Attend self-enriching events, drive company growth and all while checking out cool new working space innovations. Finish that report while lazing in our sleeping pod or make that call while going around the office on a hoverboard.
        </p>
        <p class="text-center p15">Welcome to the future of coworking.</p>
        <p class="text-center ptop"><%= link_to "Book Now", plans_path, :class => "btn btn1", :onclick => "ga('send','event','Click','Book Now');"%></p>
      </div>

      <!--network-->
      <div id="net">
        <div class="text-center">
          <img src="/assets/home/img/icon/network.png" height="60">
          <h2 class="title-header">Rub Elbows</h2>
          <hr class="line">
        </div>
        <p class="text-justify">
          Network with the best, collaborate with the rest. Meet other innovators who share the same passion. Make friends over a game of pool, ping-pong or FIFA. Everything great starts with a simple connection. 
        </p>
        <p class="text-center"><%= link_to "Book Now", plans_path, :class => "btn btn1", :onclick => "ga('send','event','Click','Book Now');"%></p>
      </div>
      <!--end-->
    </div>

    <div class="col-md-6 no-gutter scrollable">
      <div class="row scroll-image-wrapper" id="val-img">
        <img src="/assets/home/img/all/value.jpg" alt="An Affordable Coworking Space in Jakarta" height="300" width="100%">
        <div class="overlay-item">
          <div class="bottom-right">
           <h3 class="overlay-text title-header text-right">Great Value</h3>
            <hr class="line-right"> 
          </div>  
        </div>
      </div>
      <div class="row scroll-image-wrapper" id="fut-img">
        <img src="/assets/home/img/all/social.jpg" alt="Coworking Space in Jakarta With Social Benefit" height="300" width="100%">
        <div class="overlay-item">
          <div class="bottom-right">
            <h3 class="overlay-text title-header text-right">Coworking Space Is The Future</h3>
            <hr class="line-right">
          </div>
        </div>
      </div>
      <div class="row scroll-image-wrapper" id="net-img">
        <img src="/assets/home/img/all/network.jpg" alt="Coworking Space in Indonesia With Networking Benefit" style="width:100%;height:300px;">
        <div class="overlay-item">
          <div class="bottom-right">
            <h3 class="overlay-text title-header text-right">Network</h3>
            <hr class="line-right">
          </div>  
        </div>
      </div>
      <a href="#val-img" class="btn-up"><i class="fa fa-angle-up fa-2x font-white"></i></a>
      <a href="#net-img" class="btn-down"><i class="fa fa-angle-down fa-2x font-white"></i></a>
    </div>
  </div>

  <!--Mobile version-->
  <div class="row bg-grey cowork-mobile">
    <div class="owl-carousel owl-theme cowork-slider">
      <!--item 1-->
      <div class="item font-white">
        <div class="text-center">
          <img src="/assets/home/img/icon/value.png" height="60">
          <h2 class="title-header">One fits all</h2>
          <hr class="line">
        </div>
        <p class="text-justify">
          A coworking space in Indonesia, especially Jakarta, with a one price solution for all your necessities: meeting rooms, fiber-optic internet, printing and freeflow gourmet coffee. Affordable, convenient, professional. Hassle-free coworking spaces in Jakarta that offers you the flexibility you need. With futuristic workspaces that boosts your productivity, inspiration is a blink away. 
        </p>
        <p class="text-center p15">Why pay extra when you can pay less for more?</p>
        <p class="text-center ptop"><%= link_to "Book Now", plans_path, :class => "btn btn1", :onclick => "ga('send','event','Click','Book Now');"%></p>
      </div>
        
      <!--item 2-->
      <div class="item font-white">
        <div class="text-center">
          <img src="/assets/home/img/icon/the_future.png" height="60">
          <h2 class="title-header">Work hard, play hard..</h2>
          <hr class="line">
        </div>
        <p class="text-justify">
          Work hard or play hard? Why not both? Attend self-enriching events, drive company growth and all while checking out cool new working space innovations. Finish that report while lazing in our sleeping pod or make that call while going around the office on a hoverboard.
        </p>
        <p class="text-center p15">Welcome to the future of coworking.</p>
        <p class="text-center ptop"><%= link_to "Book Now", plans_path, :class => "btn btn1", :onclick => "ga('send','event','Click','Book Now');"%></p>
      </div>

      <!--item 3-->
      <div class="item font-white">
        <div class="text-center">
          <img src="/assets/home/img/icon/network.png" height="60">
          <h2 class="title-header">Rub Elbows</h2>
          <hr class="line">
        </div>
        <p class="text-justify">
          Network with the best, collaborate with the rest. Meet other innovators who share the same passion. Make friends over a game of pool, ping-pong or FIFA. Everything great starts with a simple connection. 
        </p>
        <p class="text-center"><%= link_to "Book Now", plans_path, :class => "btn btn1", :onclick => "ga('send','event','Click','Book Now');"%></p>
      </div>

    </div>
  </div>
</section>

<section>
  <div class="container-fluid">
    <img src="/assets/home/img/header/whyevhive.png" alt="" style="width:100%">
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-xs-12">
        <div class="blurb">
          <p class="text-center"><img src="/assets/home/img/icon/transparent.png" height="60"></p>
          <h3 class="text-center title-header">Transparent</h3>
          <hr class="line line-black">
          <p class="text-center">We believe trust is the foundation of a great teamwork. At our space, transparancy is encouraged wherever applicable. Surround yourself with a valuable environment to foster a team stronger than ever. </p>
        </div>
      </div>

      <div class="col-md-4 col-xs-12">
        <div class="blurb">
          <p class="text-center"><img src="/assets/home/img/icon/the_best.png" height="60"></p>
          <h3 class="text-center title-header">Best of The Best</h3>
          <hr class="line line-black">
          <p class="text-center">The fastest growing coworking space in Indonesia. With facilities that can maximize a member’s productivity, we are where collaboration matters and networking starts.</p>
        </div>
      </div>

      <div class="col-md-4 col-xs-12">
        <div class="blurb">
          <p class="text-center"><img src="/assets/home/img/icon/ecosystem.png" height="60"></p>
          <h3 class="text-center title-header">Ecosystem</h3>
          <hr class="line line-black">
          <p class="text-center">Fully supports Indonesia’s startup ecosystem. We provide private offices, meeting rooms and event spaces to support day-to-day business activities.</p> 
        </div>
      </div>

    </div>
  </div>
</section>

<script type="text/javascript">
  $(document).ready(function(){
    $(window).on("load",function(){
      $("#promoModal").modal("show");
    });

    $(".event-slider").owlCarousel({
      itemsDesktop : [1199,4],
      itemsDesktopSmall : [980,3],
      itemsTablet: [768,2],
      itemsTabletSmall: false,
      itemsMobile : [479,1],
      autoPlay:5000,
      items:3,
      navigation:false,
      pagination:true,
    });

    $(".cowork-slider").owlCarousel({
      singleItem:true,
      margin:0,
      autoHeight:false,
      navigation:false,
      pagination:true
    });

    

    $("#fut-img").on("mouseover",function(){
      $("#val").css("display","none");
      $("#net").css("display","none");
      $("#fut").fadeIn("slow");
    });

    $("#val-img").on("mouseover",function(){
      $("#fut").css("display","none");
      $("#net").css("display","none");
      $("#val").fadeIn("slow");
    });

    $("#net-img").on("mouseover",function(){
      $("#fut").css("display","none");
      $("#val").css("display","none");
      $("#net").fadeIn("slow");
    });

    $(".btn-down").on("click",function(){
      $(".btn-up").show();
      $(this).hide();
    });
    $(".btn-up").on("click",function(){
      $(".btn-down").show();
      $(this).hide();
    });

  });

</script>

<script async type="text/javascript">
  $(document).ready(function(){
    var animationEnd = "webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend";
    // $(".btn-cta").on("mouseenter",function(){
    //   $(this).addClass("animated bounce").one(animationEnd,function(){
    //     $(this).removeClass("animated bounce");
    //   });
    // });

    $(".other .container").css("opacity",0);
    $(".other .container").waypoint(function(){
      $(".other .container").addClass("animated fadeInUp");
    },{offset:'70%'});

    /*$("#event .container").css("opacity",0);*/
    $("#event .container").waypoint(function(){
      $("#event .events").addClass("animated fadeInLeft");
    },{offset:'70%'});

    $(".gallery-item").css("opacity",0);
    $("#gallery .container").css("opacity",0);
    $("#gallery").waypoint(function(){
      $(".gallery-item").addClass("animated fadeInLeft");
      $("#gallery .container").addClass("animated fadeInRight");
    },{offset:"50%"});
    // $(window).scroll(function(){
    //   if($(window).scrollTop() > 0){
    //     $("nav").css("background-color","white");
    //   }else{
    //     $("nav").css("background-color","transparent");
    //   }
    //
    // });
  });

</script>