config/routes.rb
Rails.application.routes.draw do

  get 'sitemap.xml', :to => 'sitemap#index', :defaults => {:format => 'xml'}

  get 'upcoming_events/index'

  get 'past_events/index'

  resources :schedules
  get "schedules/detail/:room_id" => "schedules#detail", as: :detail

  namespace :api, defaults: { format: :json }  do
    namespace :v1 do
      resources :schedules, :only => [:index,:show, :create, :update]
      post "receive/xendit" => "receive#xendit"
      get "receive/xendit" => "receive#xendit"
    end
  end

  namespace :managers do
    get 'books/index'
  end

  namespace :id do
    resources :blogs, :only => [:index, :show]
  end

  mount_roboto
  mount Ckeditor::Engine => '/ckeditor'
  resources :benefits, :only => [:index, :show]
  resources :careers, :only => [:index, :show]
  resources :schoolpreneurs, controller:'evhive_classes', :only => [:index, :show]
  resources :evhive_connects, :only => [:index,:create]
  resources :authors, :only => [:show]
  resources :partners, :only => [:index, :show]
  resources :events, :only => [:index, :show]
  resources :blogs, :only => [:index, :show]
  resources :categories, :only => [:show]
  resources :promos, :only => [:index, :show]
  resources :subscribes, :only => [:create]
  get 'tags/:tag', to: 'blogs#index', as: "tag"

  resources :books
  resources :payments
  resources :enquiries
  namespace :managers do
    root to: 'dashboard#index'
    resources :plans, :buildings, :locations, :blogs,:categories, :events, :benefits, :rooms,:report, :dashboard, :books, :careers, :partners, :evhive_classes, :evhive_connects, :schedules, :enquiries, :promos, :payments, :authors
    get "report/paid/:id" => "report#paid", as: :set_paid
    get "report/destroy/:id" => "report#destroy", as: :set_destroy
  end

  devise_for :managers
  resources :subscriptions do
    collection do
      get 'thank_you/:id' => "subscriptions#thank_you", as: :sub_thank
    end
  end
  resources :dashboard

  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    :sessions => "users/sessions"
  }
  resources :locations
  resources :buildings
  resources :plans

  get 'about' => 'home#about'
  get 'press' => 'blogs#press'
  get 'enquiry' => 'enquiries#new'
  get 'privacy_policy' => 'home#privacy_policy'
  get 'thank_you' => 'home#thank_you'
  get 'student_ambassador' => 'home#student_ambassador'
  get 'creative-studio', to: 'plans#creative_studio'
  get 'meeting-room', to: 'plans#meeting_room'
  get 'event-space', to: 'plans#event_space'
  get '/past_events' => 'past_events#index'
  root to: 'home#index'

end

app/models/promo.rb
class Promo < ActiveRecord::Base
end

app/controllers/managers/promos_controller.rb
class Managers::PromosController < PromosController
  layout 'manager'
  before_filter :authenticate_manager!

  def index
    @promos = Promo.all
  end
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  before_action :set_promo, only: [:show, :edit, :update, :destroy]

  # GET /promos
  # GET /promos.json
  def index
    @promos = Promo.all
  end

  # GET /promos/1
  # GET /promos/1.json
  def show
  end

  # GET /promos/new
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
  end

  # POST /promos
  # POST /promos.json
  def create
    @promo = Promo.new(promo_params)

    respond_to do |format|
      if @promo.save
        format.html { redirect_to managers_promos_path, notice: 'Promo was successfully created.' }
        format.json { render :show, status: :created, location: managers_promos_path }
      else
        format.html { render :new }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promos/1
  # PATCH/PUT /promos/1.json
  def update
    respond_to do |format|
      if @promo.update(promo_params)
        format.html { redirect_to managers_promos_path, notice: 'Promo was successfully updated.' }
        format.json { render :show, status: :ok, location: @promo }
      else
        format.html { render :edit }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo.destroy
    respond_to do |format|
      format.html { redirect_to promos_url, notice: 'Promo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo
      @promo = Promo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promo_params
      params.require(:promo).permit(:name, :description, :price)
    end
end

app/helpers/managers/promos_helper.rb
module Managers::PromosHelper
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/_form.html.erb
<%= form_for [:managers,@promo], :html => { :class => "form-horizontal event", multipart: true  } do |f| %>

  <% if @promo.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@promo.errors.count, "error") %> prohibited this event from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @promo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-md-4 col-xs-12">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-md-8 col-xs-12">
      <%= f.cktext_area :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-md-4 col-xs-12">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-md-4">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                managers_promos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/promos/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <%- model_class = Promo -%>
        <div class="card-header" data-background-color="purple">
          <h4 class="title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
        </div>
        <div class="card-content">
          <%= render :partial => 'form' %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/promos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Promos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promos.each do |promo| %>
      <tr>
        <td><%= promo.name %></td>
        <td><%= promo.description %></td>
        <td><%= promo.price %></td>
        <td><%= link_to 'Show', promo %></td>
        <td><%#= link_to 'Edit', edit_promo_path(promo) %></td>
        <td><%#= link_to 'Destroy', promo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Promo', new_promo_path %>

app/views/promos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <%- model_class = Promo -%>
        <div class="card-header" data-background-color="purple">
          <h4 class="title"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
        </div>
        <div class="card-content">
          <%= render :partial => 'form' %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/promos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @promo.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @promo.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @promo.price %>
</p>

<%#= link_to 'Edit', edit_promo_path(@promo) %> |
<%= link_to 'Back', promos_path %>