config/routes.rb
Rails.application.routes.draw do

  get 'sitemap.xml', :to => 'sitemap#index', :defaults => {:format => 'xml'}

  get 'upcoming_events/index'

  get 'past_events/index'

  resources :schedules
  get "schedules/detail/:room_id" => "schedules#detail", as: :detail

  namespace :api, defaults: { format: :json }  do
    namespace :v1 do
      resources :schedules, :only => [:index,:show, :create, :update]
      post "receive/xendit" => "receive#xendit"
      get "receive/xendit" => "receive#xendit"
    end
  end

  namespace :managers do
    get 'books/index'
  end

  namespace :id do
    resources :blogs, :only => [:index, :show]
  end

  mount_roboto
  mount Ckeditor::Engine => '/ckeditor'
  resources :benefits, :only => [:index, :show]
  resources :careers, :only => [:index, :show]
  resources :schoolpreneurs, controller:'evhive_classes', :only => [:index, :show]
  resources :evhive_connects, :only => [:index,:create]
  resources :authors, :only => [:show]
  resources :partners, :only => [:index, :show]
  resources :events, :only => [:index, :show]
  resources :blogs, :only => [:index, :show]
  resources :categories, :only => [:show]
  resources :promos, :only => [:index, :show]
  resources :subscribes, :only => [:create]
  get 'tags/:tag', to: 'blogs#index', as: "tag"

  resources :books
  resources :payments
  resources :enquiries
  namespace :managers do
    root to: 'dashboard#index'
    resources :plans, :buildings, :locations, :blogs,:categories, :events, :benefits, :rooms,:report, :dashboard, :books, :careers, :partners, :evhive_classes, :evhive_connects, :schedules, :enquiries, :promos, :payments, :authors
    get "report/paid/:id" => "report#paid", as: :set_paid
    get "report/destroy/:id" => "report#destroy", as: :set_destroy
  end

  devise_for :managers
  resources :subscriptions do
    collection do
      get 'thank_you/:id' => "subscriptions#thank_you", as: :sub_thank
    end
  end
  resources :dashboard

  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    :sessions => "users/sessions"
  }
  resources :locations
  resources :buildings
  resources :plans

  get 'about' => 'home#about'
  get 'press' => 'blogs#press'
  get 'enquiry' => 'enquiries#new'
  get 'privacy_policy' => 'home#privacy_policy'
  get 'thank_you' => 'home#thank_you'
  get 'student_ambassador' => 'home#student_ambassador'
  get 'creative-studio', to: 'plans#creative_studio'
  get 'meeting-room', to: 'plans#meeting_room'
  get 'event-space', to: 'plans#event_space'
  get '/past_events' => 'past_events#index'
  root to: 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :evhive_classes
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @evhive_classes = EvhiveClass.where("category_id = ?", @category.id)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to managers_categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: managers_categories_path }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to managers_categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: managers_categories_path }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to managers_categories_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/managers/categories_controller.rb
class Managers::CategoriesController < CategoriesController
  layout 'manager'
  before_filter :authenticate_manager!

  def index
    @categories = Category.all
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/managers/categories_helper.rb
module Managers::CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for [:managers,@category], :html => { :class => "form-horizontal event", multipart: true  } do |f| %>
  <% if @category.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@category.errors.count, "error") %> prohibited this event from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-md-4 col-xs-12">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-md-4">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                managers_categories_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', managers_categories_path %>

app/views/categories/show.html.erb
<div class="container ptop pbottom">
  <h3 class="text-center pbottom"><%= @category.name %> Classes</h3>
  <div class="row">
    <% @evhive_classes.each do|classes|%>
    <div class="col-md-4 classes">
      <%= link_to schoolpreneur_path(classes) do%>
      <div class="thumbnail">
        <%= image_tag (classes.image.url(:original))%>
        <div class="caption">
          <h5><%= classes.name %></h5>
        </div>
      </div>
      <% end %>
    </div>
  <%end%>
  </div>
  
</div>