config/routes.rb
Rails.application.routes.draw do

  get 'sitemap.xml', :to => 'sitemap#index', :defaults => {:format => 'xml'}

  get 'upcoming_events/index'

  get 'past_events/index'

  resources :schedules
  get "schedules/detail/:room_id" => "schedules#detail", as: :detail

  namespace :api, defaults: { format: :json }  do
    namespace :v1 do
      resources :schedules, :only => [:index,:show, :create, :update]
      post "receive/xendit" => "receive#xendit"
      get "receive/xendit" => "receive#xendit"
    end
  end

  namespace :managers do
    get 'books/index'
  end

  namespace :id do
    resources :blogs, :only => [:index, :show]
  end

  mount_roboto
  mount Ckeditor::Engine => '/ckeditor'
  resources :benefits, :only => [:index, :show]
  resources :careers, :only => [:index, :show]
  resources :schoolpreneurs, controller:'evhive_classes', :only => [:index, :show]
  resources :evhive_connects, :only => [:index,:create]
  resources :authors, :only => [:show]
  resources :partners, :only => [:index, :show]
  resources :events, :only => [:index, :show]
  resources :blogs, :only => [:index, :show]
  resources :categories, :only => [:show]
  resources :promos, :only => [:index, :show]
  resources :subscribes, :only => [:create]
  get 'tags/:tag', to: 'blogs#index', as: "tag"

  resources :books
  resources :payments
  resources :enquiries
  namespace :managers do
    root to: 'dashboard#index'
    resources :plans, :buildings, :locations, :blogs,:categories, :events, :benefits, :rooms,:report, :dashboard, :books, :careers, :partners, :evhive_classes, :evhive_connects, :schedules, :enquiries, :promos, :payments, :authors
    get "report/paid/:id" => "report#paid", as: :set_paid
    get "report/destroy/:id" => "report#destroy", as: :set_destroy
  end

  devise_for :managers
  resources :subscriptions do
    collection do
      get 'thank_you/:id' => "subscriptions#thank_you", as: :sub_thank
    end
  end
  resources :dashboard

  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    :sessions => "users/sessions"
  }
  resources :locations
  resources :buildings
  resources :plans

  get 'about' => 'home#about'
  get 'press' => 'blogs#press'
  get 'enquiry' => 'enquiries#new'
  get 'privacy_policy' => 'home#privacy_policy'
  get 'thank_you' => 'home#thank_you'
  get 'student_ambassador' => 'home#student_ambassador'
  get 'creative-studio', to: 'plans#creative_studio'
  get 'meeting-room', to: 'plans#meeting_room'
  get 'event-space', to: 'plans#event_space'
  get '/past_events' => 'past_events#index'
  root to: 'home#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :taggings
  has_many :tags, through: :taggings

  belongs_to :manager
  belongs_to :author
  has_attached_file :banner, styles: { medium: "300x300>", thumb: "100x100>" }, :path => ":rails_root/public/images/files/:class/:attachment/:id/:style/:filename",:url => "/images/files/:class/:attachment/:id/:style/:filename"
  validates_attachment_content_type :banner, content_type: /\Aimage\/.*\z/

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
        Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).blogs
  end

end

app/models/manager.rb
class Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :building
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    if params[:tag]
     @blogs = Blog.tagged_with(params[:tag]).order(id: :desc)
    else
     @blogs = Blog.where('lang = ? AND press = ?','english',false).order(id: :desc)
    end
  end

  def new
    @blog = Blog.new
  end

  def show
    #@related = Tagging.where("blog_id = ?",@blog.tag_id)
    @tagging = Tagging.where('blog_id = ?',@blog.id).map{|i| i.tag_id}
    @tag = Tagging.where('tag_id in (?)',@tagging).map{|j| j.blog_id}
    @related = Blog.where('id in (?)', @tag)
  end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to managers_blogs_path, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: managers_blogs_path }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to managers_blogs_path, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: managers_blogs_path }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to managers_blogs_path, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def press
    @blogs = Blog.where('press =?',true).order(id: :desc)
  end
  private

  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blog_params
    params.require(:blog).permit(:title, :meta_description, :content, :all_tags, :banner, :lang, :press, :author_id)
  end
end

app/controllers/id/blogs_controller.rb
class Id::BlogsController < ApplicationController
	before_action :set_blog, only: [:show]
  def index
		@blogs = Blog.where('lang = ? AND press = ?', 'bahasa', false).order(id: :desc)
	end

	def show
	
	end

	private

	def set_blog
		@blog = Blog.find(params[:id])
	end
end

app/controllers/managers/authors_controller.rb
class Managers::AuthorsController < AuthorsController
  layout 'manager'
  before_filter :authenticate_manager!
  @authors = Author.all
end

app/controllers/managers/benefits_controller.rb
class Managers::BenefitsController < BenefitsController
  layout 'manager'
  before_filter :authenticate_manager!
  def index
    @benefits = Benefit.all
  end
end

app/controllers/managers/blogs_controller.rb
class Managers::BlogsController < BlogsController
  layout 'manager'
  
  before_filter :authenticate_manager!
  def index
    @blogs = Blog.where('lang = ?', 'english')
    @blogs_id= Blog.where('lang = ?', 'bahasa')
    @press= Blog.where('press = ?', true)
  end
end

app/controllers/managers/books_controller.rb
class Managers::BooksController < BooksController
  def index
    if current_manager.building_id.nil?
      @books = Book.all
    else
      @books = Book.where('building_id = ?', current_manager.building_id)
    end
  end
end

app/controllers/managers/buildings_controller.rb
class Managers::BuildingsController < ApplicationController
  layout 'manager'

  before_filter :authenticate_manager!
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  # GET /plans.json
  def index
    @buildings = Building.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @building = Building.new
    @building.banners.build
  end

  # GET /plans/1/edit
  def edit
    @building.banners.build
  end

  # POST /plans
  # POST /plans.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to [:managers,@building], notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: [:managers,@building] }
      else
        format.html { render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to [:managers,@building], notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: [:managers,@building] }
      else
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to managers_buildings_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_building
    @building = Building.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def building_params
    params.require(:building).permit(:name, :address, :phone, :map, :description,:available, :meta_title, :meta_description, :tag, :location_id,:image, :spin_link, :parking_fee, banners_attributes: [:id, :image, :_destroy])
  end
end

app/controllers/managers/careers_controller.rb
class Managers::CareersController < CareersController
  layout 'manager'
  before_filter :authenticate_manager!

  def index
    @careers = Career.all
  end
  
end

app/controllers/managers/categories_controller.rb
class Managers::CategoriesController < CategoriesController
  layout 'manager'
  before_filter :authenticate_manager!

  def index
    @categories = Category.all
  end
end

app/controllers/managers/dashboard_controller.rb
class Managers::DashboardController < ApplicationController
  layout 'manager'
  
  before_filter :authenticate_manager!

  def index
  end
end

app/controllers/managers/enquiries_controller.rb
class Managers::EnquiriesController < EnquiriesController
  before_filter :authenticate_manager!
  layout 'manager'
  
  def index
    @enquiries = Enquiry.where('name is not ?', nil)
  end
end

app/controllers/managers/events_controller.rb
class Managers::EventsController < EventsController
  layout 'manager'
  before_filter :authenticate_manager!

  def index
    @events = Event.all
  end


end

app/controllers/managers/evhive_classes_controller.rb
class Managers::EvhiveClassesController < EvhiveClassesController
  layout 'manager'
  before_filter :authenticate_manager!

  def index
    @evhive_classes = EvhiveClass.all
  end
end

app/controllers/managers/evhive_connects_controller.rb
class Managers::EvhiveConnectsController < EvhiveConnectsController
  layout 'manager'
  before_filter :authenticate_manager!

  def index
    @evhive_connects = EvhiveConnect.all
  end
end

app/controllers/managers/locations_controller.rb
class Managers::LocationsController < ApplicationController
  layout 'manager'
  
  before_filter :authenticate_manager!
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /plans.json
  def index
    @locations = Location.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @location = Location.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to [:managers,@location], notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: [:managers,@location] }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to [:managers,@location], notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: [:managers,@location] }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to managers_locations_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_location
    @location = Location.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def location_params
    params.require(:location).permit(:name, :image)
  end
end

app/controllers/managers/partners_controller.rb
class Managers::PartnersController < PartnersController
  layout 'manager'
  before_filter :authenticate_manager!

  def index
    @partners = Partner.all
  end
end

app/controllers/managers/payments_controller.rb
class Managers::PaymentsController < PaymentsController
	layout 'manager'
  
	before_filter :authenticate_manager!
	
	def index
		@payments = Payment.all
	end
end

app/controllers/managers/plans_controller.rb
class Managers::PlansController < ApplicationController
  layout 'manager'

  before_filter :authenticate_manager!
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans.json
  def index
    if current_manager.building_id.nil?
      @plans = Plan.all
    else
      @plans = Plan.where('building_id = ?', current_manager.building_id)
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to [:managers,@plan], notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: [:managers,@plan] }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to [:managers,@plan], notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: [:managers,@plan] }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to admins_plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_plan
    @plan = Plan.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def plan_params
    params.require(:plan).permit(:name, :description, :price, :building_id, :quantity, :jurnal_name)
  end
end

app/views/managers/blogs/index.html.erb
<div class="container-fluid">
  <ul class="nav nav-tabs">
    <li class="active">
      <a href="#eng" data-toggle="tab">English</a>
    </li>
    <li>
      <a href="#id" data-toggle="tab">Indonesia</a>
    </li>
    <li>
      <a href="#press" data-toggle="tab">Press Release</a>
    </li>
  </ul>

  <div class="tab-content">
    <div id="eng" class="tab-pane fade in active">
      <table class="table table-striped">
          <thead>
            <tr>
              <th>Id</th>
              <th>Title</th>
              <th><%=t '.actions', :default => t("helpers.actions") %></th>
            </tr>
          </thead>
          <tbody>
            <% @blogs.each do |blog| %>
              <tr>
                <td><%= link_to blog.id, managers_blog_path(blog) %></td>
                <td><%= blog.title %></td>
                <td>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                              edit_managers_blog_path(blog), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                              managers_blog_path(blog),
                              :method => :delete,
                              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                              :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to t('.new', :default => t("helpers.links.new")),
                    new_managers_blog_path,
                    :class => 'btn btn-success btn-block' %>
    </div><!--end of english blog-->

    <div id="id" class="tab-pane fade">
      <table class="table table-striped">
          <thead>
            <tr>
              <th>Id</th>
              <th>Title</th>
              <th><%=t '.actions', :default => t("helpers.actions") %></th>
            </tr>
          </thead>
          <tbody>
            <% @blogs_id.each do |blog| %>
              <tr>
                <td><%= link_to blog.id, managers_blog_path(blog) %></td>
                <td><%= blog.title %></td>
                <td>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                              edit_managers_blog_path(blog), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                              managers_blog_path(blog),
                              :method => :delete,
                              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                              :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to t('.new', :default => t("helpers.links.new")),
                    new_managers_blog_path,
                    :class => 'btn btn-success btn-block' %>
    </div><!--end of bahasa blogs-->

    <div id="press" class="tab-pane fade">
      <table class="table table-striped">
          <thead>
            <tr>
              <th>Id</th>
              <th>Title</th>
              <th><%=t '.actions', :default => t("helpers.actions") %></th>
            </tr>
          </thead>
          <tbody>
            <% @press.each do |blog| %>
              <tr>
                <td><%= link_to blog.id, managers_blog_path(blog) %></td>
                <td><%= blog.title %></td>
                <td>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                              edit_managers_blog_path(blog), :class => 'btn btn-default btn-xs' %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                              managers_blog_path(blog),
                              :method => :delete,
                              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                              :class => 'btn btn-xs btn-danger' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to t('.new', :default => t("helpers.links.new")),
                    new_managers_blog_path,
                    :class => 'btn btn-success btn-block' %>
    </div><!--end of bahasa blogs-->
  </div>
</div>